/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * calculadora1.java
 *
 * Created on 19/06/2016, 05:12:52 PM
 */



/**
 *
 * @author Administrador
 */
public class calculadora1 extends javax.swing.JApplet {

    /** Initializes the applet calculadora1 */
    public void init() {
        try {
            java.awt.EventQueue.invokeAndWait(new Runnable() {
                public void run() {
                    initComponents();
                }
            });
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    /** This method is called from within the init() method to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtprecio = new javax.swing.JTextField();
        txtpantalla = new javax.swing.JTextField();
        jButton20 = new javax.swing.JButton();
        txtprecio1 = new javax.swing.JTextField();
        txtprecio2 = new javax.swing.JTextField();
        txtprecio3 = new javax.swing.JTextField();
        txtprecio4 = new javax.swing.JTextField();
        txtprecio5 = new javax.swing.JTextField();
        txtprecio6 = new javax.swing.JTextField();
        txtprecio7 = new javax.swing.JTextField();
        txtpantalla1 = new javax.swing.JTextField();
        txtpantalla2 = new javax.swing.JTextField();
        txtpantalla3 = new javax.swing.JTextField();
        txtpantalla4 = new javax.swing.JTextField();
        txtpantalla5 = new javax.swing.JTextField();
        txtpantalla6 = new javax.swing.JTextField();
        txtpantalla7 = new javax.swing.JTextField();
        txtpantalla8 = new javax.swing.JTextField();
        jButton18 = new javax.swing.JButton();

        txtprecio.setEditable(false);
        txtprecio.setText("1.5");
        txtprecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtprecioActionPerformed(evt);
            }
        });
        txtprecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtprecioKeyTyped(evt);
            }
        });

        txtpantalla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpantallaActionPerformed(evt);
            }
        });
        txtpantalla.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtpantallaKeyTyped(evt);
            }
        });

        jButton20.setBackground(new java.awt.Color(0, 102, 102));
        jButton20.setForeground(new java.awt.Color(255, 255, 255));
        jButton20.setText("Limpiar pantalla");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });

        txtprecio1.setEditable(false);
        txtprecio1.setText("4.5");
        txtprecio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtprecio1ActionPerformed(evt);
            }
        });
        txtprecio1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtprecio1KeyTyped(evt);
            }
        });

        txtprecio2.setEditable(false);
        txtprecio2.setText("6");
        txtprecio2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtprecio2ActionPerformed(evt);
            }
        });
        txtprecio2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtprecio2KeyTyped(evt);
            }
        });

        txtprecio3.setEditable(false);
        txtprecio3.setText("10");
        txtprecio3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtprecio3ActionPerformed(evt);
            }
        });
        txtprecio3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtprecio3KeyTyped(evt);
            }
        });

        txtprecio4.setEditable(false);
        txtprecio4.setText("6");
        txtprecio4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtprecio4ActionPerformed(evt);
            }
        });
        txtprecio4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtprecio4KeyTyped(evt);
            }
        });

        txtprecio5.setEditable(false);
        txtprecio5.setText("12");
        txtprecio5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtprecio5ActionPerformed(evt);
            }
        });
        txtprecio5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtprecio5KeyTyped(evt);
            }
        });

        txtprecio6.setEditable(false);
        txtprecio6.setText("7");
        txtprecio6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtprecio6ActionPerformed(evt);
            }
        });
        txtprecio6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtprecio6KeyTyped(evt);
            }
        });

        txtprecio7.setEditable(false);
        txtprecio7.setText("14");
        txtprecio7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtprecio7ActionPerformed(evt);
            }
        });
        txtprecio7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtprecio7KeyTyped(evt);
            }
        });

        txtpantalla1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpantalla1ActionPerformed(evt);
            }
        });
        txtpantalla1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtpantalla1KeyTyped(evt);
            }
        });

        txtpantalla2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpantalla2ActionPerformed(evt);
            }
        });
        txtpantalla2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtpantalla2KeyTyped(evt);
            }
        });

        txtpantalla3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpantalla3ActionPerformed(evt);
            }
        });
        txtpantalla3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtpantalla3KeyTyped(evt);
            }
        });

        txtpantalla4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpantalla4ActionPerformed(evt);
            }
        });
        txtpantalla4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtpantalla4KeyTyped(evt);
            }
        });

        txtpantalla5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpantalla5ActionPerformed(evt);
            }
        });
        txtpantalla5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtpantalla5KeyTyped(evt);
            }
        });

        txtpantalla6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpantalla6ActionPerformed(evt);
            }
        });
        txtpantalla6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtpantalla6KeyTyped(evt);
            }
        });

        txtpantalla7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpantalla7ActionPerformed(evt);
            }
        });
        txtpantalla7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtpantalla7KeyTyped(evt);
            }
        });

        txtpantalla8.setEditable(false);
        txtpantalla8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpantalla8ActionPerformed(evt);
            }
        });
        txtpantalla8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtpantalla8KeyTyped(evt);
            }
        });

        jButton18.setBackground(new java.awt.Color(0, 102, 102));
        jButton18.setForeground(new java.awt.Color(255, 255, 255));
        jButton18.setText("Total=");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(227, 227, 227)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtprecio2, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtprecio1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtprecio3, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtprecio4, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtprecio5, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtprecio6, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtprecio7, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtprecio, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtpantalla8, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtpantalla, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(jButton20, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtpantalla1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtpantalla2, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtpantalla3, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtpantalla4, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtpantalla5, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtpantalla6, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtpantalla7, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(124, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtpantalla, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtprecio, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jButton20, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtprecio1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtpantalla1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtprecio2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtpantalla2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtprecio3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtpantalla3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtprecio4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtpantalla4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtprecio5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtpantalla5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtprecio6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtpantalla6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtprecio7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtpantalla7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtpantalla8, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(121, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtprecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtprecioActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_txtprecioActionPerformed

    private void txtprecioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtprecioKeyTyped
        // TODO add your handling code here:
        //ESTE EVENTO NO DEJA DIGITAR LETRAS EN EL CAMPO DE TEXTO(SOLO NUMEROS 0-9 Y UN SOLO PUNTO)
        if(!Character.isDigit(evt.getKeyChar())&& evt.getKeyChar()!='.'){
            evt.consume();
        }
        if(evt.getKeyChar()=='.'&&txtprecio.getText().contains(".")){
            evt.consume();
        }
}//GEN-LAST:event_txtprecioKeyTyped

    private void txtpantallaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpantallaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpantallaActionPerformed

    private void txtpantallaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpantallaKeyTyped
        // TODO add your handling code here:

        char car = evt.getKeyChar();
        if( txtpantalla.getText().length()>=30 ) evt.consume();
        if(( car<'0' || car>'9' ))evt.consume();

    }//GEN-LAST:event_txtpantallaKeyTyped

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        // TODO add your handling code here:
        txtpantalla.setText("");
        txtpantalla1.setText("");
        txtpantalla2.setText("");
        txtpantalla3.setText("");
        txtpantalla4.setText("");
        txtpantalla5.setText("");
        txtpantalla6.setText("");
        txtpantalla7.setText("");
        txtpantalla8.setText("");
}//GEN-LAST:event_jButton20ActionPerformed

    private void txtprecio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtprecio1ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_txtprecio1ActionPerformed

    private void txtprecio1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtprecio1KeyTyped
        // TODO add your handling code here:
        //ESTE EVENTO NO DEJA DIGITAR LETRAS EN EL CAMPO DE TEXTO(SOLO NUMEROS 0-9 Y UN SOLO PUNTO)
        if(!Character.isDigit(evt.getKeyChar())&& evt.getKeyChar()!='.'){
            evt.consume();
        }
        if(evt.getKeyChar()=='.'&&txtprecio1.getText().contains(".")){
            evt.consume();
        }
}//GEN-LAST:event_txtprecio1KeyTyped

    private void txtprecio2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtprecio2ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_txtprecio2ActionPerformed

    private void txtprecio2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtprecio2KeyTyped
        // TODO add your handling code here:
}//GEN-LAST:event_txtprecio2KeyTyped

    private void txtprecio3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtprecio3ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_txtprecio3ActionPerformed

    private void txtprecio3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtprecio3KeyTyped
        // TODO add your handling code here:
        //ESTE EVENTO NO DEJA DIGITAR LETRAS EN EL CAMPO DE TEXTO(SOLO NUMEROS 0-9 Y UN SOLO PUNTO)
        if(!Character.isDigit(evt.getKeyChar())&& evt.getKeyChar()!='.'){
            evt.consume();
        }
        if(evt.getKeyChar()=='.'&&txtprecio3.getText().contains(".")){
            evt.consume();
        }
}//GEN-LAST:event_txtprecio3KeyTyped

    private void txtprecio4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtprecio4ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_txtprecio4ActionPerformed

    private void txtprecio4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtprecio4KeyTyped
        // TODO add your handling code here:
        //ESTE EVENTO NO DEJA DIGITAR LETRAS EN EL CAMPO DE TEXTO(SOLO NUMEROS 0-9 Y UN SOLO PUNTO)
        if(!Character.isDigit(evt.getKeyChar())&& evt.getKeyChar()!='.'){
            evt.consume();
        }
        if(evt.getKeyChar()=='.'&&txtprecio4.getText().contains(".")){
            evt.consume();
        }
}//GEN-LAST:event_txtprecio4KeyTyped

    private void txtprecio5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtprecio5ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_txtprecio5ActionPerformed

    private void txtprecio5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtprecio5KeyTyped
        // TODO add your handling code here:
        //ESTE EVENTO NO DEJA DIGITAR LETRAS EN EL CAMPO DE TEXTO(SOLO NUMEROS 0-9 Y UN SOLO PUNTO)
        if(!Character.isDigit(evt.getKeyChar())&& evt.getKeyChar()!='.'){
            evt.consume();
        }
        if(evt.getKeyChar()=='.'&&txtprecio5.getText().contains(".")){
            evt.consume();
        }
}//GEN-LAST:event_txtprecio5KeyTyped

    private void txtprecio6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtprecio6ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_txtprecio6ActionPerformed

    private void txtprecio6KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtprecio6KeyTyped
        // TODO add your handling code here:
        //ESTE EVENTO NO DEJA DIGITAR LETRAS EN EL CAMPO DE TEXTO(SOLO NUMEROS 0-9 Y UN SOLO PUNTO)
        if(!Character.isDigit(evt.getKeyChar())&& evt.getKeyChar()!='.'){
            evt.consume();
        }
        if(evt.getKeyChar()=='.'&&txtprecio6.getText().contains(".")){
            evt.consume();
        }
}//GEN-LAST:event_txtprecio6KeyTyped

    private void txtprecio7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtprecio7ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_txtprecio7ActionPerformed

    private void txtprecio7KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtprecio7KeyTyped
        // TODO add your handling code here:
        //ESTE EVENTO NO DEJA DIGITAR LETRAS EN EL CAMPO DE TEXTO(SOLO NUMEROS 0-9 Y UN SOLO PUNTO)
        if(!Character.isDigit(evt.getKeyChar())&& evt.getKeyChar()!='.'){
            evt.consume();
        }
        if(evt.getKeyChar()=='.'&&txtprecio7.getText().contains(".")){
            evt.consume();
        }
}//GEN-LAST:event_txtprecio7KeyTyped

    private void txtpantalla1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpantalla1ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_txtpantalla1ActionPerformed

    private void txtpantalla1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpantalla1KeyTyped
        // TODO add your handling code here:
        {
            //ESTE EVENTO NO DEJA DIGITAR LETRAS EN EL CAMPO DE TEXTO
            char car = evt.getKeyChar();
            if( txtpantalla1.getText().length()>=30 ) evt.consume();
            if(( car<'0' || car>'9' ))evt.consume();

        }
}//GEN-LAST:event_txtpantalla1KeyTyped

    private void txtpantalla2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpantalla2ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_txtpantalla2ActionPerformed

    private void txtpantalla2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpantalla2KeyTyped
        // TODO add your handling code here:
        {
            //ESTE EVENTO NO DEJA DIGITAR LETRAS EN EL CAMPO DE TEXTO
            char car = evt.getKeyChar();
            if( txtpantalla2.getText().length()>=30 ) evt.consume();
            if(( car<'0' || car>'9' ))evt.consume();

        }
}//GEN-LAST:event_txtpantalla2KeyTyped

    private void txtpantalla3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpantalla3ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_txtpantalla3ActionPerformed

    private void txtpantalla3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpantalla3KeyTyped
        // TODO add your handling code here:
        {
            //ESTE EVENTO NO DEJA DIGITAR LETRAS EN EL CAMPO DE TEXTO
            char car = evt.getKeyChar();
            if( txtpantalla3.getText().length()>=30 ) evt.consume();
            if(( car<'0' || car>'9' ))evt.consume();

        }
}//GEN-LAST:event_txtpantalla3KeyTyped

    private void txtpantalla4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpantalla4ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_txtpantalla4ActionPerformed

    private void txtpantalla4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpantalla4KeyTyped
        // TODO add your handling code here:
        {
            //ESTE EVENTO NO DEJA DIGITAR LETRAS EN EL CAMPO DE TEXTO
            char car = evt.getKeyChar();
            if( txtpantalla4.getText().length()>=30 ) evt.consume();
            if(( car<'0' || car>'9' ))evt.consume();

        }
}//GEN-LAST:event_txtpantalla4KeyTyped

    private void txtpantalla5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpantalla5ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_txtpantalla5ActionPerformed

    private void txtpantalla5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpantalla5KeyTyped
        // TODO add your handling code here:
        {
            //ESTE EVENTO NO DEJA DIGITAR LETRAS EN EL CAMPO DE TEXTO
            char car = evt.getKeyChar();
            if( txtpantalla5.getText().length()>=30 ) evt.consume();
            if(( car<'0' || car>'9' ))evt.consume();

        }
}//GEN-LAST:event_txtpantalla5KeyTyped

    private void txtpantalla6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpantalla6ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_txtpantalla6ActionPerformed

    private void txtpantalla6KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpantalla6KeyTyped
        // TODO add your handling code here:
        {
            //ESTE EVENTO NO DEJA DIGITAR LETRAS EN EL CAMPO DE TEXTO
            char car = evt.getKeyChar();
            if( txtpantalla6.getText().length()>=30 ) evt.consume();
            if(( car<'0' || car>'9' ))evt.consume();

        }
}//GEN-LAST:event_txtpantalla6KeyTyped

    private void txtpantalla7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpantalla7ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_txtpantalla7ActionPerformed

    private void txtpantalla7KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpantalla7KeyTyped
        // TODO add your handling code here:
        {
            //ESTE EVENTO NO DEJA DIGITAR LETRAS EN EL CAMPO DE TEXTO
            char car = evt.getKeyChar();
            if( txtpantalla7.getText().length()>=30 ) evt.consume();
            if(( car<'0' || car>'9' ))evt.consume();

        }
}//GEN-LAST:event_txtpantalla7KeyTyped

    private void txtpantalla8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpantalla8ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_txtpantalla8ActionPerformed

    private void txtpantalla8KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpantalla8KeyTyped
        // TODO add your handling code here:
}//GEN-LAST:event_txtpantalla8KeyTyped

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // TODO add your handling code here:
        String cadena;
        cadena=txtpantalla.getText();

        if (cadena.length()<=0) {
            txtpantalla.setText("0");

        }
        String cadena1;
        cadena1=txtpantalla1.getText();

        if (cadena1.length()<=0) {
            txtpantalla1.setText("0");

        }
        String cadena2;
        cadena2=txtpantalla2.getText();

        if (cadena2.length()<=0) {
            txtpantalla2.setText("0");

        }
        String cadena3;
        cadena3=txtpantalla3.getText();

        if (cadena3.length()<=0) {
            txtpantalla3.setText("0");

        }

        String cadena4;
        cadena4=txtpantalla4.getText();

        if (cadena4.length()<=0) {
            txtpantalla4.setText("0");

        }
        String cadena5;
        cadena5=txtpantalla5.getText();

        if (cadena5.length()<=0) {
            txtpantalla5.setText("0");

        }
        String cadena6;
        cadena6=txtpantalla6.getText();

        if (cadena6.length()<=0) {
            txtpantalla6.setText("0");

        }
        String cadena7;
        cadena7=txtpantalla7.getText();

        if (cadena7.length()<=0) {
            txtpantalla7.setText("0");

        }

        double num1 = Double.parseDouble(txtprecio.getText());
        double numero1 = Double.parseDouble(txtpantalla.getText());
        double result1 = num1 * numero1;
        double num2 = Double.parseDouble(txtprecio1.getText());
        double numero2 = Double.parseDouble(txtpantalla1.getText());
        double result2 = num2 * numero2;
        double num3 = Double.parseDouble(txtprecio2.getText());
        double numero3 = Double.parseDouble(txtpantalla2.getText());
        double result3 = num3 * numero3;
        double num4 = Double.parseDouble(txtprecio3.getText());
        double numero4 = Double.parseDouble(txtpantalla3.getText());
        double result4 = num4 * numero4;
        double num5 = Double.parseDouble(txtprecio4.getText());
        double numero5 = Double.parseDouble(txtpantalla4.getText());
        double result5 = num5 * numero5;
        double num6 = Double.parseDouble(txtprecio5.getText());
        double numero6 = Double.parseDouble(txtpantalla5.getText());
        double result6 = num6 * numero6;
        double num7 = Double.parseDouble(txtprecio6.getText());
        double numero7 = Double.parseDouble(txtpantalla6.getText());
        double result7 = num7 * numero7;
        double num8 = Double.parseDouble(txtprecio7.getText());
        double numero8 = Double.parseDouble(txtpantalla7.getText());
        double result8 = num8 * numero8;
        double resultFinal =((result1)+(result2)+(result3)+(result4)+(result5)+(result6)+(result7)+(result8));

        String valorTotal = Double.toString(resultFinal);
        txtpantalla8.setText(valorTotal);

    }//GEN-LAST:event_jButton18ActionPerformed
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton20;
    private javax.swing.JTextField txtpantalla;
    private javax.swing.JTextField txtpantalla1;
    private javax.swing.JTextField txtpantalla2;
    private javax.swing.JTextField txtpantalla3;
    private javax.swing.JTextField txtpantalla4;
    private javax.swing.JTextField txtpantalla5;
    private javax.swing.JTextField txtpantalla6;
    private javax.swing.JTextField txtpantalla7;
    private javax.swing.JTextField txtpantalla8;
    private javax.swing.JTextField txtprecio;
    private javax.swing.JTextField txtprecio1;
    private javax.swing.JTextField txtprecio2;
    private javax.swing.JTextField txtprecio3;
    private javax.swing.JTextField txtprecio4;
    private javax.swing.JTextField txtprecio5;
    private javax.swing.JTextField txtprecio6;
    private javax.swing.JTextField txtprecio7;
    // End of variables declaration//GEN-END:variables

}
